name: dartproptest
description: A property-based testing framework for Dart, inspired by QuickCheck and Hypothesis. Ported from jsproptest.
version: 0.2.0-rc.1
homepage: https://github.com/kindone/dartproptest
repository: https://github.com/kindone/dartproptest
issue_tracker: https://github.com/kindone/dartproptest/issues
documentation: https://github.com/kindone/dartproptest/blob/main/doc/index.md

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # No external dependencies for core functionality

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

topics:
  - testing
  - property-based-testing
  - quickcheck
  - bdd
  - tdd
