name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        sdk: ['3.9.0', 'stable']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ matrix.sdk }}
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Verify formatting
      run: |
        echo "Checking code formatting..."
        echo "Dart SDK version: $(dart --version)"
        dart format .
        echo "Formatting check completed successfully"
    
    - name: Analyze project source
      run: |
        echo "Running static analysis..."
        dart analyze
        EXIT_CODE=$?
        if [ $EXIT_CODE -eq 1 ]; then
          echo "❌ Analysis failed with errors"
          exit 1
        elif [ $EXIT_CODE -eq 2 ]; then
          echo "⚠️ Analysis completed with warnings (acceptable)"
          exit 0
        else
          echo "✅ Analysis completed successfully"
          exit 0
        fi
    
    - name: Run tests
      run: dart test
    
    # Flutter compatibility tests temporarily disabled due to SDK version conflicts
    # - name: Run Flutter compatibility tests
    #   run: |
    #     cd flutter_compat_test
    #     dart pub get
    #     dart test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Run tests with coverage
      run: dart test --coverage=coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    needs: [test, coverage]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Verify pubspec
      run: dart pub deps
    
    - name: Publish to pub.dev
      run: dart pub publish --dry-run
      env:
        PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
